const { Client } = require('pg');
const bcrypt = require('bcryptjs');
require('dotenv').config();

async function createAdmin() {
    const client = new Client({
        connectionString: process.env.DATABASE_URL,
        ssl: { rejectUnauthorized: false }
    });

    try {
        await client.connect();
        const username = 'admin';
        const password = 'password123';
        const hashedPassword = await bcrypt.hash(password, 10);

        // Delete existing to be safe
        await client.query('DELETE FROM "جدول_المستخدمين" WHERE "اسم_المستخدم" = $1', [username]);

        // Insert using exact same bcryptjs logic as the app
        const query = `
            INSERT INTO "جدول_المستخدمين" ("اسم_المستخدم", "كلمة_المرور", "اسم_الدور", "فعال", "permissions")
            VALUES ($1, $2, $3, $4, $5)
        `;
        await client.query(query, [
            username, 
            hashedPassword, 
            'ADMIN', 
            true, 
            JSON.stringify({
                "ادخال": true, 
                "تعديل": true, 
                "حذف": true, 
                "طباعة": true, 
                "بحث": true,
                "صلاحيات_المستخدمين": true
            })
        ]);

        console.log('--- SUCCESS ---');
        console.log(`User [${username}] created/reset with password [${password}]`);
        console.log('Hash generated by bcryptjs:', hashedPassword);
    } catch (err) {
        console.error('Error creating admin:', err);
    } finally {
        await client.end();
    }
}

createAdmin();
