// Map URL slugs to Prisma Model names and configuration
export const TABLE_CONFIG: Record<string, { model: string; title: string; searchField: string; nameField?: string }> = {
    'cities': { model: 'city', title: 'المدن والمحافظات', searchField: 'name' },
    'villages': { model: 'village', title: 'القرى والأحياء', searchField: 'name' },
    'job-titles': { model: 'jobTitle', title: 'المسميات الوظيفية', searchField: 'name' },
    'job-categories': { model: 'jobCategory', title: 'الفئات الوظيفية', searchField: 'name' },
    'appointment-types': { model: 'appointmentType', title: 'أنواع التعيين', searchField: 'name' },
    'work-statuses': { model: 'workStatus', title: 'أوضاع العمل', searchField: 'name' },
    'assigned-works': { model: 'assignedWork', title: 'الأعمال المكلف بها', searchField: 'name' },
    'universities': { model: 'university', title: 'الجامعات', searchField: 'name' },
    'colleges': { model: 'college', title: 'الكليات', searchField: 'name' },
    'institutes': { model: 'institute', title: 'المعاهد', searchField: 'name' },
    'certificate-types': { model: 'certificateType', title: 'أنواع الشهادات', searchField: 'name' },
    'educational-complexes': { model: 'educationalComplex', title: 'المجمعات التربوية', searchField: 'name' },
    'marital-statuses': { model: 'maritalStatus', title: 'الأوضاع العائلية', searchField: 'name' },
    'suwayda-secretariats': { model: 'suwaydaSecretariat', title: 'الأمانات', searchField: 'name' },
    // New Academic & Organizational lookups
    'college-departments': { model: 'collegeDepartment', title: 'أقسام الكليات', searchField: 'department_name', nameField: 'department_name' },
    'institute-departments': { model: 'instituteDepartment', title: 'أقسام المعاهد', searchField: 'department_name', nameField: 'department_name' },
    'science-colleges': { model: 'scienceCollegeDetail', title: 'تفاصيل كلية العلوم', searchField: 'branch_name', nameField: 'branch_name' },
    'high-schools': { model: 'highSchool', title: 'الثانويات', searchField: 'name' },
    'high-school-branches': { model: 'highSchoolBranch', title: 'فروع الثانوية', searchField: 'branch_name', nameField: 'branch_name' },
    'higher-college-departments': { model: 'higherCollegeDepartment', title: 'أقسام كليات عليا', searchField: 'department_name', nameField: 'department_name' },
    'higher-science-colleges': { model: 'higherScienceCollegeDetail', title: 'فروع علوم عليا', searchField: 'branch_name', nameField: 'branch_name' },
    'higher-institute-departments': { model: 'higherInstituteDepartment', title: 'أقسام معاهد عليا', searchField: 'department_name', nameField: 'department_name' },
    'ministries': { model: 'ministry', title: 'الوزارات', searchField: 'name' },
    'departments': { model: 'department', title: 'الدوائر', searchField: 'name' },
    'sections': { model: 'section', title: 'الشعب', searchField: 'name' },
    'system-links': { model: 'systemLink', title: 'جداول الربط', searchField: 'list_name', nameField: 'list_name' },
};
